### ISSUE TITLE
获取验证码报错

### ISSUE THREAD

**Issue by wenyi2372** [boris1993/tiantang-auto-harvest#49]
报错信息如下：
"message":'p' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 4

**Comment by boris1993** [comment]
不是软件问题，甜糖的接口貌似出问题了，获取手机号接口返回纯文本`404 page not found`，所以我这也就报错了。
刚刚在甜糖手机端也试过手机号登陆，确定是服务端接口挂了。
等甜糖修复吧。

**Comment by wenyi2372** [comment]
嗯 我刚手机端试也是不行 垃圾糖🤣
