### ISSUE TITLE
无法获取图形验证码

### ISSUE THREAD

**Issue by Han-GK** [boris1993/tiantang-auto-harvest#53]
![image](https://user-images.githubusercontent.com/99523510/206827094-f7d385a6-07b4-4bcd-90e4-c99caf6c872c.png)
如图所示报错，服务器出现错误
fork了您的代码，编译了win x64版本，也有相同错误

**Comment by Han-GK** [comment]
通过其他途径获取到的token，可以直接提交进去吗

**Comment by Han-GK** [comment]
![image](https://user-images.githubusercontent.com/99523510/206827419-5cb991ad-6c85-4341-a245-ffcb330133e6.png)
docker logs

**Comment by boris1993** [comment]
服务端域名变了，我尽快改过来

**Comment by boris1993** [comment]
最新的镜像已经修复了

**Comment by Han-GK** [comment]
感谢大佬，重新拉了镜像，已经恢复正常了
